### PR TITLE
Call onclose after we remove the tabs in the interface

### PR DESCRIPTION
**Pull request by arj03**
in the same way we do on clicking close

### CODE REVIEW

**Comment by mixmix** [comment]
hey @arj03 have you linked this in to prove it works for patchbay?

I don't know what your comment means, are you refering to somewhere else in the code?

**Comment by arj03** [comment]
Yes, I'm running this branch in patchbay: 

https://github.com/ssbc/patchbay/tree/fix-quote-2

And what I'm comparing is:

https://github.com/hyperhype/hypertabs/blob/master/tabs.js#L46

You can see that if I click close, onclose gets called after. This change makes it consistent.

**Comment by dominictarr** [comment]
@arj03 added you to org + npm owner, feel free to merge

**Comment by arj03** [comment]
Thanks!

**Pull request merged**
